<a href="https://colab.research.google.com/github/AJL99/CM4125/blob/main/datavis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IQ data import and trimming (like trimming the fat)

In [ ]:
import pandas as pd

In [ ]:
IQ = pd.read_csv('/content/my data/IQ_level.csv')

In [ ]:
IQ

     rank            country   IQ  education_expenditure  avg_income  avg_temp
0       1         Hong Kong   106                 1283.0     35304.0      26.2
1       2              Japan  106                 1340.0     40964.0      19.2
2       3          Singapore  106                 1428.0     41100.0      31.5
3       4            Taiwan   106                    NaN         NaN      26.9
4       5              China  104                  183.0      4654.0      19.1
..    ...                ...  ...                    ...         ...       ...
103   104  Equatorial Guinea   56                    NaN      7625.0      29.9
104   105             Gambia   55                   14.0       648.0      32.9
105   106          Guatemala   55                   92.0      2830.0      32.1
106   107       Sierra Leone   52                   16.0       412.0      30.4
107   108              Nepal   51                   22.0       595.0      24.6

[108 rows x 6 columns]

In [ ]:
IQ_trimmed = IQ[['IQ', 'country']]

In [ ]:
IQ_trimmed

      IQ            country
0    106         Hong Kong
1    106              Japan
2    106          Singapore
3    106            Taiwan
4    104              China
..   ...                ...
103   56  Equatorial Guinea
104   55             Gambia
105   55          Guatemala
106   52       Sierra Leone
107   51              Nepal

[108 rows x 2 columns]

In [ ]:
IQ_trimmed.to_csv('/content/my data/trimmed/IQ_trimmed.csv', index=False)

# Military Expenditure data import and trimming

In [ ]:
MS = pd.read_csv('/content/my data/military-spending-per-capita.csv')

In [ ]:
MS

           Entity Code  Year  military_expenditure_per_capita
0     Afghanistan  AFG  2004                             5.06
1     Afghanistan  AFG  2005                             4.78
2     Afghanistan  AFG  2006                             4.97
3     Afghanistan  AFG  2007                             8.10
4     Afghanistan  AFG  2008                             8.68
...           ...  ...   ...                              ...
4793     Zimbabwe  ZWE  2015                            27.27
4794     Zimbabwe  ZWE  2016                            25.52
4795     Zimbabwe  ZWE  2017                            23.92
4796     Zimbabwe  ZWE  2018                            29.11
4797     Zimbabwe  ZWE  2019                            37.35

[4798 rows x 4 columns]

In [ ]:
MS_trimmed = MS[MS['Year'] == 2020]

In [ ]:
MS_trimmed.drop(columns=('Code'), inplace=True)

<ipython-input-69-99407e30eace>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MS_trimmed.drop(columns=('Code'), inplace=True)

In [ ]:
MS_trimmed.rename(columns={'Entity': 'country'}, inplace=True)

<ipython-input-70-9dbd10e62e88>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MS_trimmed.rename(columns={'Entity': 'country'}, inplace=True)

In [ ]:
MS_trimmed

             country  Year  military_expenditure_per_capita
16       Afghanistan  2020                             7.18
45           Albania  2020                            77.15
78           Algeria  2020                           221.39
110           Angola  2020                            30.23
143        Argentina  2020                            64.32
...              ...   ...                              ...
4536         Ukraine  2020                           135.46
4587  United Kingdom  2020                           872.62
4620   United States  2020                          2351.14
4653         Uruguay  2020                           334.97
4768          Zambia  2020                            11.54

[151 rows x 3 columns]

In [ ]:
MS_trimmed.to_csv('/content/my data/trimmed/MS_trimmed.csv', index=False)

# Drinks data import and trimming

In [ ]:
DR = pd.read_csv('/content/my data/drinks.csv')

In [ ]:
DR

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
...,...,...,...,...,...
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

In [ ]:
DR_trimmed = DR.replace('USA', 'United States')

In [ ]:
DR_trimmed

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
...,...,...,...,...,...
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

In [ ]:
DR_trimmed.to_csv('/content/my data/trimmed/DR_trimmed.csv', index=False)

# Nobel Prize Winners data import and trimming

In [ ]:
NP = pd.read_csv('/content/my data/nobel_prize_by_winner.csv', encoding='latin-1')

In [ ]:
NP

,id,firstname,surname,born,died,bornCountry,bornCountryCode,bornCity,diedCountry,diedCountryCode,diedCity,gender,year,category,overallMotivation,share,motivation,name,city,country
0,846,Elinor,Ostrom,8/7/1933,6/12/2012,USA,US,"Los Angeles, CA",USA,US,"Bloomington, IN",female,2009.0,economics,NaN,2.0,"""for her analysis of economic governance, espe...",Indiana University,"Bloomington, IN",USA
1,846,Elinor,Ostrom,8/7/1933,6/12/2012,USA,US,"Los Angeles, CA",USA,US,"Bloomington, IN",female,2009.0,economics,NaN,2.0,"""for her analysis of economic governance, espe...",Arizona State University,"Tempe, AZ",USA
2,783,Wangari Muta,Maathai,4/1/1940,9/25/2011,Kenya,KE,Nyeri,Kenya,KE,Nairobi,female,2004.0,peace,NaN,1.0,"""for her contribution to sustainable developme...",NaN,NaN,NaN
3,230,Dorothy Crowfoot,Hodgkin,5/12/1910,7/29/1994,Egypt,EG,Cairo,United Kingdom,GB,Shipston-on-Stour,female,1964.0,chemistry,NaN,1.0,"""for her determinations by X-ray techniques of...","University of Oxford, Royal Society",Oxford,United Kingdom
4,918,Youyou,Tu,12/30/1930,0000-00-00,China,CN,Zhejiang Ningbo,NaN,NaN,NaN,female,2015.0,medicine,NaN,2.0,"""for her discoveries concerning a novel therap...",China Academy of Traditional Chinese Medicine,Beijing,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967,525,United Nations Children's Fund (UNICEF),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,org,1965.0,peace,NaN,1.0,NaN,NaN,NaN,NaN
968,527,International Labour Organization (I.L.O.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,org,1969.0,peace,NaN,1.0,NaN,NaN,NaN,NaN
969,537,Amnesty International,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,org,1977.0,peace,NaN,1.0,NaN,NaN,NaN,NaN
970,547,International Physicians for the Prevention of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,org,1985.0,peace,NaN,1.0,NaN,NaN,NaN,NaN
971,550,United Nations Peacekeeping Forces,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,org,1988.0,peace,NaN,1.0,NaN,NaN,NaN,NaN

In [ ]:
NP_trimmed = NP[['firstname', 'surname', 'bornCountry']]

In [ ]:
NP_trimmed.dropna(inplace=True)

<ipython-input-307-4da035518bbb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NP_trimmed.dropna(inplace=True)

In [ ]:
NP_trimmed.rename(columns={'bornCountry': 'country'}, inplace=True)

<ipython-input-308-8f7a4d7773bc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NP_trimmed.rename(columns={'bornCountry': 'country'}, inplace=True)

In [ ]:
NP_trimmed.replace('USA', 'United States', inplace=True)

<ipython-input-309-fec4a81cb8af>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NP_trimmed.replace('USA', 'United States', inplace=True)

In [ ]:
NP_trimmed

            firstname        surname                           country
0              Elinor         Ostrom                     United States
1              Elinor         Ostrom                     United States
2        Wangari Muta        Maathai                             Kenya
3    Dorothy Crowfoot        Hodgkin                             Egypt
4              Youyou             Tu                             China
..                ...            ...                               ...
941              Ren_         Cassin                            France
942              Carl  von Ossietzky                           Germany
943         Philip J.     Noel-Baker                    United Kingdom
944     Lester Bowles        Pearson                            Canada
945       Albert John         Lutuli  Southern Rhodesia (now Zimbabwe)

[936 rows x 3 columns]

In [ ]:
for NPfix, row in NP_trimmed.iterrows():
  if NP_trimmed.loc[NPfix].at['country'].find('\('):
    NP_trimmed['country'] = NP_trimmed['country'].str.replace(r'^.*\(', '').str.slice(4, -1)

<ipython-input-300-e86182dd8b71>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  NP_trimmed['country'] = NP_trimmed['country'].str.replace(r'^.*\(', '').split('(now ')[1][:-1][4:-1]

AttributeError: ignored

In [ ]:
for NPfix, row in NP_trimmed.iterrows():
    if NP_trimmed.loc[NPfix].at['country'].find('(') >= 0:
        split_result = NP_trimmed.loc[NPfix, 'country'].split('(now ')
        if len(split_result) >= 2:
            NP_trimmed.loc[NPfix, 'country'] = split_result[1][:-1]

<ipython-input-311-6dcb39465b9e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  NP_trimmed.loc[NPfix, 'country'] = split_result[1][:-1]

In [ ]:
NP_trimmed

            firstname        surname         country
0              Elinor         Ostrom   United States
1              Elinor         Ostrom   United States
2        Wangari Muta        Maathai           Kenya
3    Dorothy Crowfoot        Hodgkin           Egypt
4              Youyou             Tu           China
..                ...            ...             ...
941              Ren_         Cassin          France
942              Carl  von Ossietzky         Germany
943         Philip J.     Noel-Baker  United Kingdom
944     Lester Bowles        Pearson          Canada
945       Albert John         Lutuli        Zimbabwe

[936 rows x 3 columns]

In [ ]:
NP_trimmed.to_csv('/content/my data/trimmed/NP_trimmed.csv', index=False)

# Table merging

In [ ]:
filteredCSV = pd.merge(DR_trimmed, IQ_trimmed, on='country', how='inner')
filteredCSV = pd.merge(filteredCSV, MS_trimmed, on='country', how='inner')
filteredCSV = pd.merge(filteredCSV, NP_trimmed, on='country', how='inner')
filteredCSV

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,IQ,Year,military_expenditure_per_capita,firstname,surname
0,Algeria,25,0,14,0.7,77,2020,221.39,Claude,Cohen-Tannoudji
1,Algeria,25,0,14,0.7,77,2020,221.39,Claude,Cohen-Tannoudji
2,Algeria,25,0,14,0.7,77,2020,221.39,Albert,Camus
3,Argentina,193,25,221,8.3,87,2020,64.32,Bernardo Alberto,Houssay
4,Argentina,193,25,221,8.3,87,2020,64.32,C_sar,Milstein
...,...,...,...,...,...,...,...,...,...,...
835,United States,249,158,84,8.7,97,2020,2351.14,Theodore,Roosevelt
836,United States,249,158,84,8.7,97,2020,2351.14,John Raleigh,Mott
837,United States,249,158,84,8.7,97,2020,2351.14,Charles Gates,Dawes
838,United States,249,158,84,8.7,97,2020,2351.14,Cordell,Hull
839,United States,249,158,84,8.7,97,2020,2351.14,George Catlett,Marshall

In [ ]:
filteredCSV.to_csv('/content/my data/trimmed/filtered.csv')
# first merge

In [ ]:
country_count = filteredCSV.groupby('country').size().reset_index(name='number of nobel prize winners')

In [ ]:
CountedNobels = pd.merge(filteredCSV, country_count, on='country')

In [ ]:
CountedNobels

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,IQ,Year,military_expenditure_per_capita,firstname,surname,number of nobel prize winners
0,Algeria,25,0,14,0.7,77,2020,221.39,Claude,Cohen-Tannoudji,3
1,Algeria,25,0,14,0.7,77,2020,221.39,Claude,Cohen-Tannoudji,3
2,Algeria,25,0,14,0.7,77,2020,221.39,Albert,Camus,3
3,Argentina,193,25,221,8.3,87,2020,64.32,Bernardo Alberto,Houssay,4
4,Argentina,193,25,221,8.3,87,2020,64.32,C_sar,Milstein,4
...,...,...,...,...,...,...,...,...,...,...,...
835,United States,249,158,84,8.7,97,2020,2351.14,Theodore,Roosevelt,275
836,United States,249,158,84,8.7,97,2020,2351.14,John Raleigh,Mott,275
837,United States,249,158,84,8.7,97,2020,2351.14,Charles Gates,Dawes,275
838,United States,249,158,84,8.7,97,2020,2351.14,Cordell,Hull,275
839,United States,249,158,84,8.7,97,2020,2351.14,George Catlett,Marshall,275

In [ ]:
CountedNobelsTrimmed = CountedNobels.drop_duplicates(subset=['country'])
CountedNobelsTrimmed.drop(['firstname', 'surname'], axis=1, inplace=True)

<ipython-input-320-eacc620f7920>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CountedNobelsTrimmed.drop(['firstname', 'surname'], axis=1, inplace=True)

In [ ]:
CountedNobelsTrimmed

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,IQ,Year,military_expenditure_per_capita,number of nobel prize winners
0,Algeria,25,0,14,0.7,77,2020,221.39,3
3,Argentina,193,25,221,8.3,87,2020,64.32,4
7,Australia,261,72,212,10.4,99,2020,1079.86,11
18,Austria,279,75,191,9.7,99,2020,399.90,19
37,Bangladesh,0,0,0,0.0,75,2020,27.68,1
38,Belgium,295,84,212,10.5,98,2020,471.21,9
47,Brazil,245,145,16,7.2,83,2020,92.85,1
48,Bulgaria,231,252,94,10.3,91,2020,179.50,1
49,Canada,240,122,100,8.2,100,2020,602.90,18
67,Chile,130,124,172,7.6,88,2020,240.67,2
69,China,79,192,8,5.0,104,2020,175.29,12
81,Colombia,159,76,3,4.2,83,2020,181.13,2
83,Costa Rica,149,87,11,4.4,88,2020,0.00,1
84,Croatia,230,87,254,10.2,95,2020,252.10,1
85,Denmark,224,81,278,10.4,98,2020,855.18,11
96,Egypt,6,4,1,0.2,78,2020,44.03,6
102,Finland,263,133,97,10.0,101,2020,737.73,3
105,France,127,151,370,11.8,97,2020,808.09,56
161,Germany,346,117,175,11.3,100,2020,629.77,89
250,Ghana,31,3,10,1.8,61,2020,7.72,1
251,Greece,133,112,218,8.3,91,2020,508.62,1
252,Guatemala,53,69,2,2.2,55,2020,19.13,2
254,Hungary,234,215,185,11.3,99,2020,249.42,9
263,Iceland,233,61,78,6.6,99,2020,0.00,1
264,India,9,114,0,2.2,77,2020,52.82,8
272,Indonesia,5,1,0,0.1,80,2020,34.35,1
273,Iran,0,0,0,0.0,81,2020,188.41,2
275,Ireland,313,118,165,11.4,95,2020,231.77,5
280,Israel,63,69,9,2.5,93,2020,2507.58,6
286,Italy,85,42,237,6.5,95,2020,478.34,20
306,Japan,77,202,16,7.0,106,2020,388.60,29
335,Kenya,58,22,2,1.8,74,2020,20.57,1
336,Lithuania,343,244,56,12.9,95,2020,430.02,3
339,Luxembourg,236,133,271,11.4,100,2020,782.03,2
341,Mexico,238,68,5,5.5,87,2020,47.44,3
344,Morocco,12,6,10,0.5,71,2020,130.88,2
346,New Zealand,203,79,175,9.3,99,2020,624.48,3
349,Nigeria,42,5,2,9.1,68,2020,12.46,1
350,Norway,169,71,129,6.7,98,2020,1311.98,13
363,Pakistan,0,0,0,0.0,81,2020,46.97,4
367,Poland,343,215,56,10.9,96,2020,344.20,30
397,Portugal,194,67,339,11.0,93,2020,454.96,3
400,South Korea,140,16,9,9.8,103,2020,892.06,2
402,Romania,297,122,167,10.4,88,2020,297.69,5
407,South Africa,225,76,81,8.2,69,2020,53.13,9
416,Spain,284,157,112,10.0,95,2020,372.83,7
423,Sweden,152,60,186,7.2,98,2020,639.02,30
453,Switzerland,185,100,280,10.2,100,2020,658.82,17
470,Turkey,51,22,7,1.4,87,2020,210.16,3
473,Ukraine,206,237,45,8.9,91,2020,135.46,5
478,United Kingdom,219,126,195,10.4,99,2020,872.62,87
565,United States,249,158,84,8.7,97,2020,2351.14,275

In [ ]:
CountedNobelsTrimmed.to_csv('/content/my data/trimmed/WorkingData.csv', index=False)